Cascade of changes in GCshCmdty/Sec/Curr-IDs after major change in module "gnucash-base", commit 91c3d12fd06888f98198a55a0f33486a305dc414.
Exception: GCshFileStats -- that has nothing to do with the above
(it's the rest of an unsuccessful experiment) and has been checked-in by
accident (nothing dramatic, though).